/**
 * OPAL language definitions — verbs, functions, data types, and their documentation.
 * This serves as the single source of truth for IntelliSense, hover info, and diagnostics.
 */

export interface OpalItem {
  name: string;
  kind: "verb" | "function" | "type" | "keyword" | "operator";
  category: string;
  signature?: string;
  description: string;
  documentation?: string;
  parameters?: OpalParameter[];
  returnType?: string;
  accelerable?: boolean;
}

export interface OpalParameter {
  name: string;
  type: string;
  description: string;
  optional?: boolean;
  defaultValue?: string;
}

// ---------------------------------------------------------------------------
// OPAL Verbs
// ---------------------------------------------------------------------------

export const OPAL_VERBS: OpalItem[] = [
  // Filter verbs
  {
    name: "filter",
    kind: "verb",
    category: "Filter",
    signature: "filter <condition>",
    description: "Select rows matching a boolean condition.",
    documentation:
      "Analogous to SQL WHERE. Returns only rows where the expression evaluates to true.",
    accelerable: true,
  },
  {
    name: "filter_last",
    kind: "verb",
    category: "Filter",
    signature: "filter_last <condition>",
    description: "Filter applied after aggregation instead of before.",
    accelerable: false,
  },
  {
    name: "topk",
    kind: "verb",
    category: "Filter",
    signature: "topk <n>, <column>",
    description: "Return the top K rows ordered by column descending.",
    accelerable: false,
  },
  {
    name: "bottomk",
    kind: "verb",
    category: "Filter",
    signature: "bottomk <n>, <column>",
    description: "Return the bottom K rows ordered by column ascending.",
    accelerable: false,
  },
  {
    name: "limit",
    kind: "verb",
    category: "Filter",
    signature: "limit <n>",
    description: "Limit the output to the first N rows.",
    accelerable: false,
  },
  {
    name: "ever",
    kind: "verb",
    category: "Filter",
    signature: "ever <condition>",
    description:
      "Include all rows from groups where the condition was ever true.",
    accelerable: true,
  },
  {
    name: "never",
    kind: "verb",
    category: "Filter",
    signature: "never <condition>",
    description:
      "Include all rows from groups where the condition was never true.",
    accelerable: true,
  },
  {
    name: "always",
    kind: "verb",
    category: "Filter",
    signature: "always <condition>",
    description:
      "Include all rows from groups where the condition was always true.",
    accelerable: true,
  },
  {
    name: "sample",
    kind: "verb",
    category: "Filter",
    signature: "sample <fraction>",
    description: "Randomly sample a fraction of rows.",
    accelerable: true,
  },

  // Projection verbs
  {
    name: "make_col",
    kind: "verb",
    category: "Projection",
    signature: "make_col <name>:<expression>, ...",
    description: "Create or replace columns using expressions.",
    documentation:
      "Adds new columns or overwrites existing ones. Multiple columns can be created in one statement.",
    accelerable: true,
  },
  {
    name: "pick_col",
    kind: "verb",
    category: "Projection",
    signature: "pick_col <col1>, <col2>, ...",
    description: "Select specific columns, dropping all others.",
    accelerable: true,
  },
  {
    name: "rename_col",
    kind: "verb",
    category: "Projection",
    signature: "rename_col <new_name>:<old_name>",
    description: "Rename one or more columns.",
    accelerable: true,
  },
  {
    name: "drop_col",
    kind: "verb",
    category: "Projection",
    signature: "drop_col <col1>, <col2>, ...",
    description: "Remove columns from the output.",
    accelerable: true,
  },
  {
    name: "set_col",
    kind: "verb",
    category: "Projection",
    signature: "set_col <name>:<expression>",
    description: "Set a column value (create if not exists, update if it does).",
    accelerable: true,
  },
  {
    name: "flatten",
    kind: "verb",
    category: "Projection",
    signature: "flatten <array_column>",
    description: "Expand array values into separate rows.",
    accelerable: true,
  },
  {
    name: "extract_regex",
    kind: "verb",
    category: "Projection",
    signature: 'extract_regex <column>, /(?P<name>pattern)/',
    description: "Extract named capture groups from a column using regex.",
    accelerable: true,
  },
  {
    name: "parse_json",
    kind: "verb",
    category: "Projection",
    signature: "parse_json <column>",
    description: "Parse a JSON string column into an object.",
    accelerable: true,
  },

  // Aggregate verbs
  {
    name: "statsby",
    kind: "verb",
    category: "Aggregate",
    signature: "statsby <agg_col>:<agg_func>, ..., group_by(<col>, ...)",
    description: "Aggregate rows grouped by specified columns.",
    documentation:
      "Similar to SQL GROUP BY. Computes aggregate functions over groups defined by group_by columns.",
    accelerable: false,
  },
  {
    name: "timechart",
    kind: "verb",
    category: "Aggregate",
    signature: "timechart <interval>, <agg_col>:<agg_func>",
    description: "Aggregate data into time-based buckets.",
    documentation:
      "Creates a time series by bucketing rows into intervals and applying aggregate functions.",
    accelerable: true,
  },
  {
    name: "align",
    kind: "verb",
    category: "Aggregate",
    signature: "align <interval>, <agg_col>:<agg_func>",
    description: "Align time series data to a uniform interval.",
    accelerable: true,
  },
  {
    name: "aggregate",
    kind: "verb",
    category: "Aggregate",
    signature: "aggregate <agg_col>:<agg_func>, ...",
    description: "Compute aggregate functions over all input rows.",
    accelerable: false,
  },
  {
    name: "rollup",
    kind: "verb",
    category: "Aggregate",
    signature: "rollup <agg_col>:<agg_func>",
    description: "Aggregate with hierarchical group-by rollup.",
    accelerable: false,
  },
  {
    name: "histogram",
    kind: "verb",
    category: "Aggregate",
    signature: "histogram <column>, bins:<n>",
    description: "Create a histogram from a numeric column.",
    accelerable: false,
  },
  {
    name: "pivot",
    kind: "verb",
    category: "Aggregate",
    signature: "pivot <pivot_col>, <value_col>:<agg_func>",
    description: "Pivot rows into columns.",
    accelerable: false,
  },
  {
    name: "unpivot",
    kind: "verb",
    category: "Aggregate",
    signature: "unpivot <col1>, <col2>, ...",
    description: "Unpivot columns into rows.",
    accelerable: false,
  },
  {
    name: "dedup",
    kind: "verb",
    category: "Aggregate",
    signature: "dedup <col1>, <col2>, ...",
    description: "Remove duplicate rows based on the specified columns.",
    accelerable: false,
  },
  {
    name: "distinct",
    kind: "verb",
    category: "Aggregate",
    signature: "distinct <col1>, <col2>, ...",
    description: "Return distinct values of the specified columns.",
    accelerable: false,
  },
  {
    name: "fill",
    kind: "verb",
    category: "Aggregate",
    signature: "fill <column>, <value>",
    description: "Fill null values in a column with a specified value.",
    accelerable: true,
  },
  {
    name: "merge_events",
    kind: "verb",
    category: "Aggregate",
    signature: "merge_events <options>",
    description: "Merge consecutive events into sessions.",
    accelerable: false,
  },
  {
    name: "make_session",
    kind: "verb",
    category: "Aggregate",
    signature: "make_session <options>",
    description: "Create session objects from sequential events.",
    accelerable: false,
  },
  {
    name: "make_reference",
    kind: "verb",
    category: "Aggregate",
    signature: "make_reference <options>",
    description: "Build a reference table from aggregated data.",
    accelerable: false,
  },
  {
    name: "bucketize",
    kind: "verb",
    category: "Aggregate",
    signature: "bucketize <options>",
    description: "Bucket numeric values into ranges.",
    accelerable: false,
  },
  {
    name: "timestats",
    kind: "verb",
    category: "Aggregate",
    signature: "timestats <interval>, <agg_col>:<agg_func>",
    description: "Compute time-based statistics.",
    accelerable: true,
  },

  // Join verbs
  {
    name: "join",
    kind: "verb",
    category: "Join",
    signature: "join <on_condition>, <dataset>",
    description: "Inner join with another dataset.",
    documentation:
      "Combines rows from two datasets where the join condition is true. Only matching rows are returned.",
    accelerable: false,
  },
  {
    name: "leftjoin",
    kind: "verb",
    category: "Join",
    signature: "leftjoin <on_condition>, <dataset>",
    description:
      "Left outer join — all rows from the left plus matching from the right.",
    accelerable: false,
  },
  {
    name: "fulljoin",
    kind: "verb",
    category: "Join",
    signature: "fulljoin <on_condition>, <dataset>",
    description: "Full outer join — all rows from both sides.",
    accelerable: false,
  },
  {
    name: "union",
    kind: "verb",
    category: "Join",
    signature: "union <dataset>",
    description: "Combine rows from two datasets vertically.",
    accelerable: true,
  },
  {
    name: "lookup",
    kind: "verb",
    category: "Join",
    signature: "lookup <key>, <dataset>",
    description: "Enrich rows by looking up values from a reference dataset.",
    accelerable: true,
  },
  {
    name: "lookup_ip_info",
    kind: "verb",
    category: "Join",
    signature: "lookup_ip_info <ip_column>",
    description: "Enrich IP addresses with geo-location information.",
    accelerable: true,
  },
  {
    name: "exists",
    kind: "verb",
    category: "Join",
    signature: "exists <condition>, <dataset>",
    description: "Filter rows where a matching row exists in another dataset.",
    accelerable: false,
  },
  {
    name: "not_exists",
    kind: "verb",
    category: "Join",
    signature: "not_exists <condition>, <dataset>",
    description:
      "Filter rows where no matching row exists in another dataset.",
    accelerable: false,
  },
  {
    name: "follow",
    kind: "verb",
    category: "Join",
    signature: "follow <condition>, <dataset>",
    description: "Correlate events in time order — find events that follow.",
    accelerable: false,
  },
  {
    name: "follow_not",
    kind: "verb",
    category: "Join",
    signature: "follow_not <condition>, <dataset>",
    description: "Find events that are NOT followed by matching events.",
    accelerable: false,
  },
  {
    name: "surrounding",
    kind: "verb",
    category: "Join",
    signature: "surrounding <condition>, <dataset>",
    description:
      "Find events surrounding a matching event within a time window.",
    accelerable: false,
  },
  {
    name: "update_resource",
    kind: "verb",
    category: "Join",
    signature: "update_resource <dataset>",
    description: "Update a resource dataset with new data.",
    accelerable: false,
  },

  // Metadata verbs
  {
    name: "set_label",
    kind: "verb",
    category: "Metadata",
    signature: "set_label <column>",
    description: "Set the label column used for display purposes.",
    accelerable: true,
  },
  {
    name: "set_link",
    kind: "verb",
    category: "Metadata",
    signature: "set_link <column>, <target_dataset>",
    description: "Create a link from a column to another dataset.",
    accelerable: true,
  },
  {
    name: "set_valid_from",
    kind: "verb",
    category: "Metadata",
    signature: "set_valid_from <column>",
    description: "Set the valid_from timestamp column for resource data.",
    accelerable: true,
  },
  {
    name: "set_primary_key",
    kind: "verb",
    category: "Metadata",
    signature: "set_primary_key <col1>, <col2>, ...",
    description: "Set the primary key columns for a resource dataset.",
    accelerable: true,
  },
  {
    name: "make_resource",
    kind: "verb",
    category: "Metadata",
    signature: "make_resource options(...)",
    description: "Convert an event stream into a resource dataset.",
    accelerable: true,
  },
  {
    name: "make_event",
    kind: "verb",
    category: "Metadata",
    signature: "make_event",
    description: "Convert data into event format.",
    accelerable: true,
  },
  {
    name: "interface",
    kind: "verb",
    category: "Metadata",
    signature: "interface <name>, <options>",
    description: "Define an output interface for a dataset.",
    accelerable: true,
  },
  {
    name: "publish",
    kind: "verb",
    category: "Metadata",
    signature: "publish <name>",
    description: "Publish the dataset as a named output.",
    accelerable: true,
  },

  // Metrics verbs
  {
    name: "delta",
    kind: "verb",
    category: "Metrics",
    signature: "delta <column>",
    description: "Compute the delta (difference) between consecutive values.",
    accelerable: true,
  },
  {
    name: "rate",
    kind: "verb",
    category: "Metrics",
    signature: "rate <column>",
    description: "Compute the per-second rate of change.",
    accelerable: true,
  },
  {
    name: "gauge",
    kind: "verb",
    category: "Metrics",
    signature: "gauge <column>",
    description: "Interpret a metric column as a gauge.",
    accelerable: true,
  },
  {
    name: "cumulativeCounter",
    kind: "verb",
    category: "Metrics",
    signature: "cumulativeCounter <column>",
    description: "Interpret a metric column as a cumulative counter.",
    accelerable: true,
  },

  // Sort / display
  {
    name: "order_by",
    kind: "verb",
    category: "Sort",
    signature: "order_by <column> [asc|desc]",
    description: "Sort rows by one or more columns.",
    accelerable: false,
  },
  {
    name: "sort",
    kind: "verb",
    category: "Sort",
    signature: "sort <column> [asc|desc]",
    description: "Alias for order_by.",
    accelerable: false,
  },
  {
    name: "colshow",
    kind: "verb",
    category: "Display",
    signature: "colshow <col1>, <col2>, ...",
    description: "Show specified columns in the output.",
    accelerable: true,
  },
  {
    name: "colhide",
    kind: "verb",
    category: "Display",
    signature: "colhide <col1>, <col2>, ...",
    description: "Hide specified columns from the output.",
    accelerable: true,
  },
];

// ---------------------------------------------------------------------------
// OPAL Functions
// ---------------------------------------------------------------------------

export const OPAL_FUNCTIONS: OpalItem[] = [
  // Aggregate functions
  {
    name: "count",
    kind: "function",
    category: "Aggregate",
    signature: "count(expr?)",
    description: "Count the number of rows.",
    returnType: "int64",
  },
  {
    name: "count_distinct",
    kind: "function",
    category: "Aggregate",
    signature: "count_distinct(expr)",
    description: "Count distinct values.",
    returnType: "int64",
  },
  {
    name: "count_distinct_approx",
    kind: "function",
    category: "Aggregate",
    signature: "count_distinct_approx(expr)",
    description: "Approximate distinct count (HyperLogLog).",
    returnType: "int64",
  },
  {
    name: "sum",
    kind: "function",
    category: "Aggregate",
    signature: "sum(expr)",
    description: "Sum of values.",
    returnType: "float64",
  },
  {
    name: "avg",
    kind: "function",
    category: "Aggregate",
    signature: "avg(expr)",
    description: "Average of values.",
    returnType: "float64",
  },
  {
    name: "min",
    kind: "function",
    category: "Aggregate",
    signature: "min(expr)",
    description: "Minimum value.",
    returnType: "varies",
  },
  {
    name: "max",
    kind: "function",
    category: "Aggregate",
    signature: "max(expr)",
    description: "Maximum value.",
    returnType: "varies",
  },
  {
    name: "any_not_null",
    kind: "function",
    category: "Aggregate",
    signature: "any_not_null(expr)",
    description: "Return any non-null value from the group.",
    returnType: "varies",
  },
  {
    name: "first",
    kind: "function",
    category: "Aggregate",
    signature: "first(expr)",
    description: "First value in the group.",
    returnType: "varies",
  },
  {
    name: "last",
    kind: "function",
    category: "Aggregate",
    signature: "last(expr)",
    description: "Last value in the group.",
    returnType: "varies",
  },
  {
    name: "percentile",
    kind: "function",
    category: "Aggregate",
    signature: "percentile(expr, p)",
    description: "Compute the p-th percentile (0-1).",
    returnType: "float64",
  },
  {
    name: "median",
    kind: "function",
    category: "Aggregate",
    signature: "median(expr)",
    description: "Median value (50th percentile).",
    returnType: "float64",
  },
  {
    name: "stddev",
    kind: "function",
    category: "Aggregate",
    signature: "stddev(expr)",
    description: "Standard deviation.",
    returnType: "float64",
  },
  {
    name: "variance",
    kind: "function",
    category: "Aggregate",
    signature: "variance(expr)",
    description: "Variance.",
    returnType: "float64",
  },
  {
    name: "string_agg",
    kind: "function",
    category: "Aggregate",
    signature: "string_agg(expr, delimiter)",
    description: "Concatenate string values with a delimiter.",
    returnType: "string",
  },
  {
    name: "array_agg",
    kind: "function",
    category: "Aggregate",
    signature: "array_agg(expr)",
    description: "Collect values into an array.",
    returnType: "array",
  },
  {
    name: "group_by",
    kind: "function",
    category: "Aggregate",
    signature: "group_by(col, ...)",
    description: "Specify grouping columns in aggregate verbs.",
    returnType: "varies",
  },

  // String functions
  {
    name: "concat",
    kind: "function",
    category: "String",
    signature: "concat(a, b, ...)",
    description: "Concatenate values into a string.",
    returnType: "string",
  },
  {
    name: "concat_strings",
    kind: "function",
    category: "String",
    signature: "concat_strings(a, b, ...)",
    description: "Concatenate string values.",
    returnType: "string",
  },
  {
    name: "upper",
    kind: "function",
    category: "String",
    signature: "upper(str)",
    description: "Convert string to uppercase.",
    returnType: "string",
  },
  {
    name: "lower",
    kind: "function",
    category: "String",
    signature: "lower(str)",
    description: "Convert string to lowercase.",
    returnType: "string",
  },
  {
    name: "trim",
    kind: "function",
    category: "String",
    signature: "trim(str)",
    description: "Remove leading and trailing whitespace.",
    returnType: "string",
  },
  {
    name: "length",
    kind: "function",
    category: "String",
    signature: "length(str)",
    description: "Length of a string.",
    returnType: "int64",
  },
  {
    name: "substring",
    kind: "function",
    category: "String",
    signature: "substring(str, start, length?)",
    description: "Extract a substring.",
    returnType: "string",
  },
  {
    name: "replace",
    kind: "function",
    category: "String",
    signature: "replace(str, old, new)",
    description: "Replace occurrences of a substring.",
    returnType: "string",
  },
  {
    name: "split",
    kind: "function",
    category: "String",
    signature: "split(str, delimiter)",
    description: "Split a string into an array.",
    returnType: "array",
  },
  {
    name: "split_part",
    kind: "function",
    category: "String",
    signature: "split_part(str, delimiter, index)",
    description: "Split and return the N-th part.",
    returnType: "string",
  },
  {
    name: "regex_match",
    kind: "function",
    category: "String",
    signature: "regex_match(str, pattern)",
    description: "Test if a string matches a regex pattern.",
    returnType: "bool",
  },
  {
    name: "regex_extract",
    kind: "function",
    category: "String",
    signature: "regex_extract(str, pattern, group?)",
    description: "Extract matching group from a regex.",
    returnType: "string",
  },
  {
    name: "regex_replace",
    kind: "function",
    category: "String",
    signature: "regex_replace(str, pattern, replacement)",
    description: "Replace matches of a regex pattern.",
    returnType: "string",
  },
  {
    name: "strpos",
    kind: "function",
    category: "String",
    signature: "strpos(str, substring)",
    description: "Find position of substring (1-based).",
    returnType: "int64",
  },
  {
    name: "left",
    kind: "function",
    category: "String",
    signature: "left(str, n)",
    description: "Return leftmost N characters.",
    returnType: "string",
  },
  {
    name: "right",
    kind: "function",
    category: "String",
    signature: "right(str, n)",
    description: "Return rightmost N characters.",
    returnType: "string",
  },
  {
    name: "lpad",
    kind: "function",
    category: "String",
    signature: "lpad(str, length, pad_str)",
    description: "Left-pad a string to a given length.",
    returnType: "string",
  },
  {
    name: "rpad",
    kind: "function",
    category: "String",
    signature: "rpad(str, length, pad_str)",
    description: "Right-pad a string to a given length.",
    returnType: "string",
  },
  {
    name: "to_string",
    kind: "function",
    category: "String",
    signature: "to_string(value)",
    description: "Convert a value to its string representation.",
    returnType: "string",
  },

  // Time functions
  {
    name: "parse_timestamp",
    kind: "function",
    category: "Time",
    signature: "parse_timestamp(str, format?)",
    description: "Parse a string into a timestamp.",
    returnType: "timestamp",
  },
  {
    name: "format_time",
    kind: "function",
    category: "Time",
    signature: "format_time(ts, format)",
    description: "Format a timestamp as a string.",
    returnType: "string",
  },
  {
    name: "from_seconds",
    kind: "function",
    category: "Time",
    signature: "from_seconds(n)",
    description: "Convert UNIX epoch seconds to timestamp.",
    returnType: "timestamp",
  },
  {
    name: "from_milliseconds",
    kind: "function",
    category: "Time",
    signature: "from_milliseconds(n)",
    description: "Convert epoch milliseconds to timestamp.",
    returnType: "timestamp",
  },
  {
    name: "from_microseconds",
    kind: "function",
    category: "Time",
    signature: "from_microseconds(n)",
    description: "Convert epoch microseconds to timestamp.",
    returnType: "timestamp",
  },
  {
    name: "from_nanoseconds",
    kind: "function",
    category: "Time",
    signature: "from_nanoseconds(n)",
    description: "Convert epoch nanoseconds to timestamp.",
    returnType: "timestamp",
  },
  {
    name: "now",
    kind: "function",
    category: "Time",
    signature: "now()",
    description: "Current timestamp.",
    returnType: "timestamp",
  },
  {
    name: "ago",
    kind: "function",
    category: "Time",
    signature: "ago(duration)",
    description: "Timestamp in the past by the given duration.",
    returnType: "timestamp",
  },
  {
    name: "date_trunc",
    kind: "function",
    category: "Time",
    signature: "date_trunc(part, ts)",
    description: "Truncate timestamp to the specified part (hour, day, etc.).",
    returnType: "timestamp",
  },
  {
    name: "date_part",
    kind: "function",
    category: "Time",
    signature: "date_part(part, ts)",
    description: "Extract a part (year, month, etc.) from a timestamp.",
    returnType: "int64",
  },
  {
    name: "date_add",
    kind: "function",
    category: "Time",
    signature: "date_add(part, n, ts)",
    description: "Add a number of intervals to a timestamp.",
    returnType: "timestamp",
  },
  {
    name: "date_diff",
    kind: "function",
    category: "Time",
    signature: "date_diff(part, ts1, ts2)",
    description: "Difference between two timestamps in the given unit.",
    returnType: "int64",
  },
  {
    name: "bin",
    kind: "function",
    category: "Time",
    signature: "bin(ts, interval)",
    description: "Bin a timestamp into intervals.",
    returnType: "timestamp",
  },

  // Semistructured functions
  {
    name: "object_keys",
    kind: "function",
    category: "Semistructured",
    signature: "object_keys(obj)",
    description: "Return the keys of an object as an array.",
    returnType: "array",
  },
  {
    name: "array_length",
    kind: "function",
    category: "Semistructured",
    signature: "array_length(arr)",
    description: "Return the number of elements in an array.",
    returnType: "int64",
  },
  {
    name: "array_contains",
    kind: "function",
    category: "Semistructured",
    signature: "array_contains(arr, value)",
    description: "Check if an array contains a value.",
    returnType: "bool",
  },
  {
    name: "array_distinct",
    kind: "function",
    category: "Semistructured",
    signature: "array_distinct(arr)",
    description: "Remove duplicate elements from an array.",
    returnType: "array",
  },
  {
    name: "array_flatten",
    kind: "function",
    category: "Semistructured",
    signature: "array_flatten(arr)",
    description: "Flatten a nested array.",
    returnType: "array",
  },
  {
    name: "get_field",
    kind: "function",
    category: "Semistructured",
    signature: "get_field(obj, key)",
    description: "Get a field value from an object.",
    returnType: "varies",
  },
  {
    name: "has_field",
    kind: "function",
    category: "Semistructured",
    signature: "has_field(obj, key)",
    description: "Check if an object has a field.",
    returnType: "bool",
  },
  {
    name: "drop_fields",
    kind: "function",
    category: "Semistructured",
    signature: "drop_fields(obj, key1, key2, ...)",
    description: "Remove fields from an object.",
    returnType: "object",
  },
  {
    name: "make_object",
    kind: "function",
    category: "Semistructured",
    signature: "make_object(key1, val1, key2, val2, ...)",
    description: "Create an object from key-value pairs.",
    returnType: "object",
  },
  {
    name: "make_array",
    kind: "function",
    category: "Semistructured",
    signature: "make_array(val1, val2, ...)",
    description: "Create an array from values.",
    returnType: "array",
  },
  {
    name: "object_merge",
    kind: "function",
    category: "Semistructured",
    signature: "object_merge(obj1, obj2)",
    description: "Merge two objects together.",
    returnType: "object",
  },
  {
    name: "flatten_all",
    kind: "function",
    category: "Semistructured",
    signature: "flatten_all(obj)",
    description: "Recursively flatten a nested object into columns.",
    returnType: "object",
  },

  // Math functions
  {
    name: "abs",
    kind: "function",
    category: "Math",
    signature: "abs(n)",
    description: "Absolute value.",
    returnType: "float64",
  },
  {
    name: "ceil",
    kind: "function",
    category: "Math",
    signature: "ceil(n)",
    description: "Round up to nearest integer.",
    returnType: "int64",
  },
  {
    name: "floor",
    kind: "function",
    category: "Math",
    signature: "floor(n)",
    description: "Round down to nearest integer.",
    returnType: "int64",
  },
  {
    name: "round",
    kind: "function",
    category: "Math",
    signature: "round(n, decimals?)",
    description: "Round to nearest integer or specified decimal places.",
    returnType: "float64",
  },
  {
    name: "pow",
    kind: "function",
    category: "Math",
    signature: "pow(base, exponent)",
    description: "Raise to a power.",
    returnType: "float64",
  },
  {
    name: "sqrt",
    kind: "function",
    category: "Math",
    signature: "sqrt(n)",
    description: "Square root.",
    returnType: "float64",
  },
  {
    name: "log",
    kind: "function",
    category: "Math",
    signature: "log(n)",
    description: "Natural logarithm.",
    returnType: "float64",
  },
  {
    name: "log10",
    kind: "function",
    category: "Math",
    signature: "log10(n)",
    description: "Base-10 logarithm.",
    returnType: "float64",
  },
  {
    name: "greatest",
    kind: "function",
    category: "Math",
    signature: "greatest(a, b, ...)",
    description: "Return the greatest value among arguments.",
    returnType: "varies",
  },
  {
    name: "least",
    kind: "function",
    category: "Math",
    signature: "least(a, b, ...)",
    description: "Return the least value among arguments.",
    returnType: "varies",
  },
  {
    name: "clamp",
    kind: "function",
    category: "Math",
    signature: "clamp(value, min, max)",
    description: "Constrain a value between min and max.",
    returnType: "float64",
  },

  // Type / cast functions
  {
    name: "typeof",
    kind: "function",
    category: "Type",
    signature: "typeof(expr)",
    description: "Return the data type of an expression as a string.",
    returnType: "string",
  },
  {
    name: "is_null",
    kind: "function",
    category: "Type",
    signature: "is_null(expr)",
    description: "Check if value is null.",
    returnType: "bool",
  },
  {
    name: "is_not_null",
    kind: "function",
    category: "Type",
    signature: "is_not_null(expr)",
    description: "Check if value is not null.",
    returnType: "bool",
  },
  {
    name: "coalesce",
    kind: "function",
    category: "Type",
    signature: "coalesce(a, b, ...)",
    description: "Return first non-null value.",
    returnType: "varies",
  },
  {
    name: "if_null",
    kind: "function",
    category: "Type",
    signature: "if_null(expr, default)",
    description: "Return default if expr is null.",
    returnType: "varies",
  },
  {
    name: "cast",
    kind: "function",
    category: "Type",
    signature: "cast(expr, type)",
    description: "Cast expression to a specified type.",
    returnType: "varies",
  },
  {
    name: "to_int",
    kind: "function",
    category: "Type",
    signature: "to_int(expr)",
    description: "Convert to int64.",
    returnType: "int64",
  },
  {
    name: "to_float",
    kind: "function",
    category: "Type",
    signature: "to_float(expr)",
    description: "Convert to float64.",
    returnType: "float64",
  },
  {
    name: "to_bool",
    kind: "function",
    category: "Type",
    signature: "to_bool(expr)",
    description: "Convert to boolean.",
    returnType: "bool",
  },
  {
    name: "to_timestamp",
    kind: "function",
    category: "Type",
    signature: "to_timestamp(expr)",
    description: "Convert to timestamp.",
    returnType: "timestamp",
  },

  // Network functions
  {
    name: "ip_is_private",
    kind: "function",
    category: "Network",
    signature: "ip_is_private(ip)",
    description: "Check if IP is in a private range.",
    returnType: "bool",
  },
  {
    name: "ip_is_loopback",
    kind: "function",
    category: "Network",
    signature: "ip_is_loopback(ip)",
    description: "Check if IP is a loopback address.",
    returnType: "bool",
  },
  {
    name: "cidr_match",
    kind: "function",
    category: "Network",
    signature: "cidr_match(ip, cidr)",
    description: "Check if IP matches a CIDR range.",
    returnType: "bool",
  },
  {
    name: "parse_ip",
    kind: "function",
    category: "Network",
    signature: "parse_ip(str)",
    description: "Parse a string into an IP address.",
    returnType: "string",
  },

  // Window functions
  {
    name: "row_number",
    kind: "function",
    category: "Window",
    signature: "row_number()",
    description: "Assign a sequential row number.",
    returnType: "int64",
  },
  {
    name: "rank",
    kind: "function",
    category: "Window",
    signature: "rank()",
    description: "Assign a rank with gaps for ties.",
    returnType: "int64",
  },
  {
    name: "dense_rank",
    kind: "function",
    category: "Window",
    signature: "dense_rank()",
    description: "Assign a rank without gaps for ties.",
    returnType: "int64",
  },
  {
    name: "lag",
    kind: "function",
    category: "Window",
    signature: "lag(expr, offset?, default?)",
    description: "Access a previous row's value.",
    returnType: "varies",
  },
  {
    name: "lead",
    kind: "function",
    category: "Window",
    signature: "lead(expr, offset?, default?)",
    description: "Access a following row's value.",
    returnType: "varies",
  },
  {
    name: "cumulative_sum",
    kind: "function",
    category: "Window",
    signature: "cumulative_sum(expr)",
    description: "Running cumulative sum.",
    returnType: "float64",
  },
];

// ---------------------------------------------------------------------------
// OPAL Data Types
// ---------------------------------------------------------------------------

export const OPAL_DATA_TYPES: OpalItem[] = [
  {
    name: "string",
    kind: "type",
    category: "Type",
    description: "UTF-8 text string.",
  },
  {
    name: "int64",
    kind: "type",
    category: "Type",
    description: "64-bit signed integer.",
  },
  {
    name: "float64",
    kind: "type",
    category: "Type",
    description: "64-bit floating-point number.",
  },
  {
    name: "bool",
    kind: "type",
    category: "Type",
    description: "Boolean value (true or false).",
  },
  {
    name: "timestamp",
    kind: "type",
    category: "Type",
    description: "Point in time with nanosecond precision.",
  },
  {
    name: "duration",
    kind: "type",
    category: "Type",
    description: "Time duration (e.g. 5m, 1h, 30s).",
  },
  {
    name: "object",
    kind: "type",
    category: "Type",
    description: "Key-value map (JSON object).",
  },
  {
    name: "array",
    kind: "type",
    category: "Type",
    description: "Ordered list of values.",
  },
  {
    name: "variant",
    kind: "type",
    category: "Type",
    description: "Union type that can hold any OPAL value.",
  },
];

// ---------------------------------------------------------------------------
// OPAL Keywords / Operators
// ---------------------------------------------------------------------------

export const OPAL_KEYWORDS: OpalItem[] = [
  {
    name: "and",
    kind: "keyword",
    category: "Logical",
    description: "Logical AND operator.",
  },
  {
    name: "or",
    kind: "keyword",
    category: "Logical",
    description: "Logical OR operator.",
  },
  {
    name: "not",
    kind: "keyword",
    category: "Logical",
    description: "Logical NOT operator.",
  },
  {
    name: "in",
    kind: "keyword",
    category: "Logical",
    description: "Membership test — check if value is in a set.",
  },
  {
    name: "not_in",
    kind: "keyword",
    category: "Logical",
    description: "Inverse membership test.",
  },
  {
    name: "contains",
    kind: "keyword",
    category: "Logical",
    description: "Substring containment test.",
  },
  {
    name: "not_contains",
    kind: "keyword",
    category: "Logical",
    description: "Inverse substring containment test.",
  },
  {
    name: "starts_with",
    kind: "keyword",
    category: "Logical",
    description: "String prefix test.",
  },
  {
    name: "ends_with",
    kind: "keyword",
    category: "Logical",
    description: "String suffix test.",
  },
  {
    name: "like",
    kind: "keyword",
    category: "Logical",
    description: "SQL-style pattern matching with % and _ wildcards.",
  },
  {
    name: "not_like",
    kind: "keyword",
    category: "Logical",
    description: "Inverse SQL-style pattern matching.",
  },
  {
    name: "matches",
    kind: "keyword",
    category: "Logical",
    description: "Regex pattern matching.",
  },
  {
    name: "true",
    kind: "keyword",
    category: "Constant",
    description: "Boolean true literal.",
  },
  {
    name: "false",
    kind: "keyword",
    category: "Constant",
    description: "Boolean false literal.",
  },
  {
    name: "null",
    kind: "keyword",
    category: "Constant",
    description: "Null literal — represents absence of a value.",
  },
  {
    name: "asc",
    kind: "keyword",
    category: "Sort",
    description: "Sort ascending.",
  },
  {
    name: "desc",
    kind: "keyword",
    category: "Sort",
    description: "Sort descending.",
  },
  {
    name: "label",
    kind: "keyword",
    category: "Reference",
    description: "Reference a linked field label (e.g. label(^Session)).",
  },
];

// ---------------------------------------------------------------------------
// Convenience: all items combined
// ---------------------------------------------------------------------------

export const ALL_OPAL_ITEMS: OpalItem[] = [
  ...OPAL_VERBS,
  ...OPAL_FUNCTIONS,
  ...OPAL_DATA_TYPES,
  ...OPAL_KEYWORDS,
];

/**
 * Lookup an OPAL item by name (case-insensitive).
 */
export function findOpalItem(name: string): OpalItem | undefined {
  const lower = name.toLowerCase();
  return ALL_OPAL_ITEMS.find((item) => item.name.toLowerCase() === lower);
}

/**
 * Get all OPAL verb names.
 */
export function getVerbNames(): string[] {
  return OPAL_VERBS.map((v) => v.name);
}

/**
 * Get all OPAL function names.
 */
export function getFunctionNames(): string[] {
  return OPAL_FUNCTIONS.map((f) => f.name);
}
